services:
  - postgresql

language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

env:
  - KEX_DB_URL=postgresql://postgres:@localhost/kex_access_control_test

before_script:
  - psql -c 'create database kex_access_control_test;' -U postgres
  - npm run build

script:
  - npm run ci